### PR TITLE
Starting to modernize Gradle

### PR DESCRIPTION
**Pull request by scribe**
This is a draft because I still don't know what all the dependencies need to be modernized, and I need to figure out why upgrading causes 3 tests to fail.

### CODE REVIEW

**Comment by lesserwhirls** [comment]
It looks like the failures are due to the mocks returning empty values rather than `null` values?

**Comment by scribe** [comment]
> It looks like the failures are due to the mocks returning empty values rather than `null` values?

I think so? But I worry swapping something else has changed the real behavior

**Comment by scribe** [comment]
I'm heavily tempted to say we go with the newest behavior, but I also don't feel like that's my call to make? Empty elements are easier to deal with than nulls most of the time?

**Comment by lesserwhirls** [comment]
Yeah, I'm +1 for empty objects over nulls. @RachelTucker, what do you think?

**Comment by scribe** [comment]
@blitt How much should we try to preserve the current behavior of the SDK vs modernizing it?

**Comment by RachelTucker** [comment]
Would an empty Boolean be `false` and an empty Integer be `0` with the new behavior? The reason why some values are nullable to begin with is because a value not being returned in a response payload has different meaning than a default value being returned. One example of the difference in meaning is written up in GOSDK-36.

**Comment by lesserwhirls** [comment]
> Would an empty Boolean be `false` and an empty Integer be `0` with the new behavior? The reason why some values are nullable to begin with is because a value not being returned in a response payload has different meaning than a default value being returned. One example of the difference in meaning is written up in GOSDK-36.

In this case, the issue is how`jackson-dataformat-xml` handles `<tag/>` vs `<tag></tag>` prior to coercion, so the question would be if BPs XML treats those as having a different meaning or not. Prior to version `2.12.0`, `<tag/>` would be treated as `null`, but `<tag></tag>` would be treated as `""`. Starting with `2.12.0`, the behavior is that both are treated as `""` (unless `xsi:nil` is specified (with proper namespace) on the element, and possibly that the xsd indicates that it is `nillable`, I think). A little more info can be found [here](https://github.com/FasterXML/jackson-dataformat-xml/issues/411).

If I tell the `XmlMapper` to treat empty as `null`, the three failing tests in this PR pass. I think the thing to do is to keep the behavior as-is, but maybe However, as long as BP does not make a distinction between the two different empty element forms, I would suggest we consider changing it in `5.5.x`.

**Comment by RachelTucker** [comment]
It looks like BP currently returns `<tag></tag>` when things are null, not `<tag/>`.

**Comment by lesserwhirls** [comment]
Ok, so by BP convention the empty element in the form of `<tag/>` means nil value, as opposed to something like:

~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   ...
   <ele xsi:nil="true"/> 
   ...
</root>
~~~

We'll make sure to keep the prior behavior and not look to change it in the future.

**Pull request closed without merging**
