### PR TITLE
JSDK-276: Updated TapeType to String

### PR DESCRIPTION
**Pull request by RachelTucker**

### CODE REVIEW

**Comment by shabtaisharon** [comment]
in the java project are you still merging to master or should it be merged to dev?

**Comment by shabtaisharon** [comment]
ok, i dont see a dev branch so the answer is no

**Comment by rpmoore** [comment]
@shabtaisharon this project is still configured for master, we have not updated any of the SDKs to use the new branching scheme.

**Comment by RachelTucker** [comment]
@rpmoore should we update?

**Comment by rpmoore** [comment]
@RachelTucker the codacy scan called out two places where we are importing java.lang.String.  This shouldn't need to be imported.  Is there a reason this is happening?

**Comment by RachelTucker** [comment]
Its related to how autogen determines imports. Do you want me to update autogen?

**Comment by rpmoore** [comment]
@RachelTucker let's leave the current branching structure

**Comment by rpmoore** [comment]
@RachelTucker we should look at it, but let's go ahead and get this merged for now.  Go ahead and create a bug to track this in autogen.

**Pull request merged**
